version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10-stretch
    steps:
      - checkout
      - run: |
          pwd
          ls -la
          docker --version
          which docker
          docker run --rm ubuntu echo hi
          make bin
