version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          pwd
          ls -la
          env | grep -i aws
          echo $somesecret
          cat ~/.aws/config
          make bin
