version: 2
jobs:
  ubuntu:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run: cat /etc/lsb-release
  centos:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: cat /etc/redhat-release
workflows:
  version: 2
  build:
    jobs:
      - ubuntu
      - centos
